version: "2"
run:
  go: "1.25"
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - gosec
    - govet
    - ineffassign
    - intrange
    - makezero
    - mirror
    - misspell
    - mnd
    - nakedret
    - nilerr
    - nilnesserr
    - noctx
    - nolintlint
    - paralleltest
    - perfsprint
    - prealloc
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testableexamples
    - testifylint
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    tagliatelle:
      case:
        rules:
          json: snake
        use-field-name: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - e2e/
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - e2e/
